// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWn_K7csVE5Lg6dvgvZivc-_w8-MKeC6k',
    appId: '1:746568507265:web:9b7d08abb5ce4d56779280',
    messagingSenderId: '746568507265',
    projectId: 'chat-app-a90e8',
    authDomain: 'chat-app-a90e8.firebaseapp.com',
    storageBucket: 'chat-app-a90e8.firebasestorage.app',
    measurementId: 'G-DZXM12YQ3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzq6bd_BsKN7DgTT0_8TN_eQSHz0VXcI',
    appId: '1:746568507265:android:22f07b2531bc982c779280',
    messagingSenderId: '746568507265',
    projectId: 'chat-app-a90e8',
    storageBucket: 'chat-app-a90e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKBIr0tPzhNyBAE6lyvD9KxhYgY3BUec',
    appId: '1:746568507265:ios:ee90094f021ff0db779280',
    messagingSenderId: '746568507265',
    projectId: 'chat-app-a90e8',
    storageBucket: 'chat-app-a90e8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKBIr0tPzhNyBAE6lyvD9KxhYgY3BUec',
    appId: '1:746568507265:ios:ee90094f021ff0db779280',
    messagingSenderId: '746568507265',
    projectId: 'chat-app-a90e8',
    storageBucket: 'chat-app-a90e8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWn_K7csVE5Lg6dvgvZivc-_w8-MKeC6k',
    appId: '1:746568507265:web:87f7f64daa2b9319779280',
    messagingSenderId: '746568507265',
    projectId: 'chat-app-a90e8',
    authDomain: 'chat-app-a90e8.firebaseapp.com',
    storageBucket: 'chat-app-a90e8.firebasestorage.app',
    measurementId: 'G-CG4GRBJ2SP',
  );
}
